{{- range .Values.api.users }}
---
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: {{ .role }}
    epinio.io/test: "test"
  name: {{ include "epinio-truncate" (print "user-" .username) }}
  namespace: {{ $.Release.Namespace }}
stringData:
  username: {{ .username }}
  password: {{ .passwordBcrypt }}
  namespaces: |
    {{ join "\n" .workspaces -}}
{{- end }}
