apiVersion: application.epinio.io/v1
kind: AppChart
metadata:
  namespace: {{ .Release.Namespace }}
  name: standard
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: epinio-standard-app-chart
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  shortDescription: Epinio standard deployment
  description: Epinio standard support chart for application deployment
  helmChart: https://github.com/epinio/helm-charts/releases/download/epinio-application-0.1.18/epinio-application-0.1.18.tgz
