apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.nginxSSLRedirect | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  labels:
    app.kubernetes.io/name: epinio
  name: epinio
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
  {{- end }}
  rules:
  - host: "epinio.{{ .Values.global.domain }}"
    http:
      paths:
  {{- if ".Values.epinio-ui.enabled" }}
      - backend:
          service:
            name: epinio-ui
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  {{- end }}
      - backend:
          service:
            name: epinio-server
            port:
              number: 80
        path: /api
        pathType: ImplementationSpecific
      - backend:
          service:
            name: epinio-server
            port:
              number: 80
        path: /wapi
        pathType: ImplementationSpecific
      - backend:
          service:
            name: epinio-server
            port:
              number: 80
        path: /ready
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - "epinio.{{ .Values.global.domain }}"
    secretName: epinio-tls
