
# htpasswd encoded credentials for access to the registry.
# Must be set on deployment.
auth:
  htpasswd: ~

registry:
  image: registry:2.7.1
  imagePullPolicy: IfNotPresent

nginx:
  image: nginx:1.19.3
  imagePullPolicy: IfNotPresent

# We create a service with type `NodePort` only in
# local deployment as Kubelet cannot access the
# secured registry because there is no way to add
# registry CA to kubelet.
createNodePort: true
