---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: epinio-server
  namespace: tekton-staging
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: epinio-server-role
  namespace: tekton-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: epinio-server
subjects:
- kind: ServiceAccount
  name: epinio-server
  namespace: epinio

