name: Build-images

on:
  push:
    branches: [ main ]
    paths:
    - 'images/linkerd-Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CFCIBOT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CFCIBOT_DOCKERHUB_PASSWORD }}
      - name: Build linkerd
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: images/linkerd-Dockerfile
          tags: splatform/epinio-linkerd:2.10.2
          build-args: |
            LINKERD_VERSION=stable-2.10.2
            LINKERD_CHECKSUM=7021232b50368b247e8d5226d381a654327f610c4f61d6719dc6fd6e46284035
            KUBECTL_VERSION=v1.21.0
            KUBECTL_CHECKSUM=9f74f2fa7ee32ad07e17211725992248470310ca1988214518806b39b1dad9f0
