name: UI-CI

on:
  workflow_dispatch:
    inputs:
      dashboard_version:
        description: "Target specific Rancher dashboard version"
        required: false
        default: "epinio-v0.3.3"

jobs:
  installation:
    runs-on: ui-e2e-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install K3s - Helm - Rancher
        env:
          MY_HOSTNAME: $(hostnamectl hostname)
          DASHBOARD_VERSION: ${{ github.events.inputs.dashboard_version }} 
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          HELM_VERSION: 3.7.0
        run: |
          #export MY_HOSTNAME=$(hostnamectl hostname)
          make e2e-ci
 
  cypress-run:
    needs:
      - installation
    runs-on: ui-e2e-1
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      env:
        RANCHER_USER: admin
        RANCHER_PASSWORD: rancherpassword
        RANCHER_URL: https://k3s-opensusetw/dashboard
        CLUSTER_NAME: local
        SYSTEM_DOMAIN: 192.168.121.160.omg.howdoi.website
        CORS: https://k3s-opensusetw
      options: --add-host k3s-opensusetw:192.168.121.160
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Specify Browser since container image is compile with Firefox
          browser: chrome
          spec: |
            cypress/integration/unit_tests/first_connexion.spec.ts
            cypress/integration/unit_tests/installation.spec.ts
            cypress/integration/unit_tests/menu.spec.ts

  delete-cluster:
    if: always()
    needs: [installation, cypress-run]
    runs-on: ui-e2e-1
    steps:
      - name: Delete k3s cluster
        run: |
          sudo /usr/local/bin/k3s-uninstall.sh

